### ISSUE TITLE
Operações de cadastro\remoção\relatório de BINAs

### ISSUE THREAD

**Issue by hugouchoasborges** [totalvoice/totalvoice-python#3]
- Como um usuário da API Totalvoice:
seria interessante a existência de tais funcionalidades

- Para:
a automatização do cadastro de telefone dos funcionários de uma empresa no sistema Totalvoice, sem a necessidade de entrar pelo site e cadastrar manualmente cada funcionário

**Comment by dilowagner** [comment]
Olá @HugoUchoasBorges, obrigado por contribuir! :+1: 
Liberamos essa funcionalidade a pouco tempo na API (beta)

https://api2.totalvoice.com.br/doc/#!/Minha_Conta/post_bina

Vamos atualizar a lib de python.

Valeu cara! Abraço!

**Comment by dilowagner** [comment]
Olá @HugoUchoasBorges realizamos o merge e publicamos uma nova versão: 1.2.0 com essa funcionalidade.
Mas uma vez... obrigado por contribuir
